# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-wiki-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: media-wiki
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: media-wiki-db-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: media-wiki-db
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
